"""Reconcile `tests/conftest.py`'s network counter against an independent one.

    .venv/bin/python tests/network_reconciliation.py

**Why this exists.** Round 2 reported `0 blocked / 0 unguarded / 0 remote DNS / 0
loopback` for a run in which an independently installed probe measured 5 remote
DNS resolutions and 12 outbound connects to github.com and
release-assets.githubusercontent.com, and the tests passed. The counter was
switched off exactly when the guard was lifted, and the DNS target was stored in a
form the loopback classifier could never match. Three of the four numbers were
structurally incapable of moving, and I reported them as a clean run.

That is the failure mode this file removes. The counter in conftest is written by
the same author as the metric, sits inside the process it measures, and can be
edited to be wrong in the same commit that reads it. A second counter, installed
from *outside* the repo before anything else runs, makes a reported zero
falsifiable: if the two disagree, the run is wrong and this exits non-zero.

**How the independent half is installed.** A generated `sitecustomize.py` on
`PYTHONPATH`, so CPython imports it during interpreter startup -- before pytest,
before `conftest.py`, before anything in this repository has had a chance to patch
anything. It wraps the same three functions as conftest and writes its records to
a JSON file at interpreter exit.

The two counters are not expected to be equal. conftest's own tests deliberately
attempt connections, and it only ever *sees* what passes through the wrappers; the
independent shim sees those too, plus anything that bypassed conftest. So the
check is one-sided and strict in the direction that matters: **the independent
counter must not miss anything the conftest counter saw.** A conftest record with
no independent counterpart means conftest counted something that did not happen, or
classified it wrongly -- which is the round-2 defect in its other form.

Deliberately not a pytest test: it launches a subprocess and compares across two
processes, so it runs as its own step (wired into `tests.yml` and the mutation
harness) rather than inside a session it is supposed to audit.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PYTHON = ROOT / ".venv/bin/python"
OUT = Path(tempfile.gettempdir()) / "nfl_offline_reconciliation.json"

SITECUSTOMIZE = '''\
"""Generated by tests/network_reconciliation.py. Installed from outside the repo.

Wraps the same three socket entry points conftest.py wraps, into a counter that
conftest cannot reach, and writes the records out at interpreter exit.
"""
import atexit, json, os, socket

RECORDS = []
_O_CONNECT = socket.socket.connect
_O_CREATE = socket.create_connection
_O_GETADDR = socket.getaddrinfo


def _dns(host):
    if isinstance(host, bytes):
        return host.decode("utf-8", "replace")
    return str(host)


def _addr(args):
    for a in args:
        if isinstance(a, (tuple, list)) and a and isinstance(a[0], (str, bytes)):
            return _dns(a[0])
    return "<unparsed>"


def _connect(self, address, *a, **k):
    RECORDS.append(["connect", _addr((self, address))])
    return _O_CONNECT(self, address, *a, **k)


def _create(address, *a, **k):
    RECORDS.append(["connect", _addr((address,))])
    return _O_CREATE(address, *a, **k)


def _getaddrinfo(host, *a, **k):
    RECORDS.append(["dns", _dns(host)])
    return _O_GETADDR(host, *a, **k)


socket.socket.connect = _connect
socket.create_connection = _create
socket.getaddrinfo = _getaddrinfo


@atexit.register
def _dump():
    with open(os.environ["NFL_OFFLINE_RECONCILE_OUT"], "w") as fh:
        json.dump(RECORDS, fh)
'''

LOOPBACK = {"localhost", "127.0.0.1", "::1", "0.0.0.0", "0", "testserver", ""}
# The full label is the key, not a prefix of it. An earlier version keyed on
# `DNS to`, which collapsed the two DNS lines into one and silently dropped a
# number -- the same class of defect this file exists to catch, in the checker
# that was supposed to catch it.
#
# The trailing text matters. conftest annotates the lines a reader is most likely
# to care about -- anything non-zero -- with a `<- ...` note, so a pattern anchored
# to end-of-line parsed only the zeros. That is round 2's blindness reproduced
# inside the checker written to catch it: the first version of this regex matched
# two of the four lines and reported the missing two as a defect in conftest rather
# than as a defect in itself. Anchored on the number, not on the end of the line.
#
# Two ways this pattern was wrong, both found by this file failing on its own
# output rather than by inspection:
#
# * it required a space after each label prefix, and the line reads
#   `connects made, guard lifted` -- a comma. So that line never matched and the
#   checker reported a missing number instead of reporting the real traffic.
# * it was anchored to end-of-line, so it matched only the lines conftest does NOT
#   annotate. conftest puts a `<- ...` note on exactly the lines a reader cares
#   about -- anything non-zero -- so the checker could only ever read zeros.
#   That is round 2's blindness reproduced inside the tool written to catch it.
# The whole label is inside the capture group, so the two DNS lines stay distinct
# keys. With the label split across the group, `DNS to a non-loopback host` and
# `DNS to loopback` both normalised to `DNS to`, the ambiguity guard fired, and the
# checker could not say which number it was looking at.
SUMMARY_RE = re.compile(
    r"^\s{4}((?:connects blocked|connects made|DNS to).*?)\s*:\s*(\d+)", re.M
)


def _reported(out: str) -> dict:
    """conftest's four numbers, keyed on the full label."""
    found: dict[str, int] = {}
    for match in SUMMARY_RE.finditer(out):
        key = re.sub(r"\s+", " ", match.group(1)).strip()
        value = int(match.group(2))
        if key in found:
            raise SystemExit(
                f"conftest printed two different numbers for {key!r}; the summary is "
                "ambiguous and this comparison would be meaningless"
            )
        found[key] = value
    return found


def main() -> int:
    if not PYTHON.exists():
        print(f"no interpreter at {PYTHON}", file=sys.stderr)
        return 2

    OUT.unlink(missing_ok=True)
    shim_dir = Path(tempfile.mkdtemp(prefix="nfl-offline-reconcile-"))
    (shim_dir / "sitecustomize.py").write_text(SITECUSTOMIZE)
    env = {
        **os.environ,
        "PYTHONPATH": os.pathsep.join([str(shim_dir), str(ROOT / "src")]),
        "NFL_OFFLINE_RECONCILE_OUT": str(OUT),
    }

    proc = subprocess.run(
        [str(PYTHON), "-m", "pytest", "-q", "tests"],
        cwd=ROOT, capture_output=True, text=True, env=env,
    )
    out = proc.stdout + proc.stderr

    reported = _reported(out)
    independent = json.loads(OUT.read_text()) if OUT.exists() else []
    # Counted, not deduplicated. A set here made the independent side smaller than
    # the conftest side purely by collapsing repeats, which would have read as
    # "conftest counted something that did not happen" -- the accusation this file
    # exists to make, arrived at by a bug in the accuser.
    indep_connect_rows = [tuple(r) for r in independent if r[0] == "connect"]
    indep_connect = set(indep_connect_rows)
    indep_dns = [r[1] for r in independent if r[0] == "dns"]
    indep_remote_dns = [h for h in indep_dns if h.strip("[]").lower() not in LOOPBACK]

    print("=" * 72)
    print("network reconciliation: conftest's counter vs an independent sitecustomize shim")
    print("=" * 72)
    print(f"conftest reported        : {reported or 'NOT FOUND'}")
    print(f"independent connects seen : {len(indep_connect_rows)} "
          f"({len(indep_connect)} distinct)  {sorted(indep_connect)[:6]}")
    print(f"independent DNS seen      : {len(indep_dns)}  {sorted(set(indep_dns))[:6]}")
    print(f"independent remote DNS    : {len(indep_remote_dns)}")
    print()

    problems = []
    missing = {"connects blocked (guard up)", "connects made, guard lifted",
               "DNS to a non-loopback host", "DNS to loopback"} - set(reported)
    if missing:
        problems.append(
            f"conftest's summary is missing {sorted(missing)} -- fewer numbers than there "
            "are things to report, so a zero is not being shown for all of them"
        )
    if not reported:
        problems.append(
            "conftest's summary was not found in the output -- the four numbers are "
            "not being printed, so nothing can be reconciled against them"
        )
    if not independent:
        problems.append(
            "the independent shim recorded nothing at all, so it is not installed and "
            "this comparison is vacuous"
        )

    # The direction that matters: anything conftest claimed must be visible to a
    # counter it cannot influence. conftest may legitimately see FEWER (its own
    # tests clean up after themselves), never more.
    for kind, count in reported.items():
        expected = {
            "connects blocked (guard up)": len(indep_connect_rows),
            "connects made, guard lifted": len(indep_connect_rows),
            "DNS to a non-loopback host": len(indep_remote_dns),
            "DNS to loopback": len([h for h in indep_dns if h.strip("[]").lower() in LOOPBACK]),
        }.get(kind)
        if expected is None:
            continue
        if count > expected:
            problems.append(
                f"conftest reported {count} for {kind!r} but the independent counter saw "
                f"{expected}. conftest is counting something that did not happen, or "
                f"classifying it wrongly."
            )
        elif count < expected:
            print(
                f"  note: conftest saw {count} {kind} against the shim's {expected} -- "
                "expected, because conftest's own tests undo their records"
            )

    if proc.returncode != 0:
        problems.append(f"the suite itself failed (pytest exit {proc.returncode})")

    if problems:
        print("\nRECONCILIATION FAILED:")
        for problem in problems:
            print(f"  - {problem}")
        print("\npytest output tail:")
        print("\n".join(out.splitlines()[-25:]))
        return 1

    print("reconciled: conftest reported nothing the independent counter could not see")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
